## Wifi
WIFI_CREDS = "[[\"MY_SSID\",\"MY_WIFI_PASSWD\"]]"

## Data collection constants
# Choose a unique device ID for your device, e.g. "yourname-co2-temperature"
DEVICE_ID = None

# Public/anonymous connection info for our supabase instance
SUPABASE_POST_URL = "https://nowoepphtlvvczgexvrb.supabase.co/rest/v1/iot"
SUPABASE_KEY = "<YOUR SUPABASE API KEY>"
